version: '3.8'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    
    depends_on:
      - db
    networks:
      - docker-network
    ports:
      - "8000:8000" 

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'nikted'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: '123456'
      DB_HOST: localhost
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - docker-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 123456
    ports:
      - "5000:80"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge


